### ISSUE TITLE
Push to docker hub

### ISSUE THREAD

**Issue by james-choncholas** [LePetitBloc/bitcoind-prometheus-exporter#2]
Love the container, any chance you could push to docker hub?

**Comment by lutangar** [comment]
Glad you like it!

Here you go https://hub.docker.com/r/lepetitbloc/bitcoind-exporter/
```
docker pull lepetitbloc/bitcoind-exporter
```

At the moment, the approach is quite naive, it's only building master branch, suggestions & PRs are most welcome.
